name: semantic-search-food
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pyarrow
  - matplotlib
  - pillow
  - ipykernel
  - pip
  - pip:
      - nltk
      - unidecode
